### Import the necessary package and create the test and train dataset

In [1]:
import pandas as pd

train_data = pd.read_excel('Data_Train.xlsx')
test_data = pd.read_excel('Test_set.xlsx')

In [2]:
train_data.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897  
1    05:50         13:15   7h 25m     2 stops         No info   7662  
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882  
3    18:05         23:30   5h 25m      1 stop         No info   6218  
4    16:50         21:35   4h 45m      1 stop         No info  13302

## EDA on train_data 

In [3]:
train_data.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [4]:
len(train_data.columns)

11

In [5]:
len(train_data)

10683

In [6]:
train_data.shape

(10683, 11)

In [7]:
train_data.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [8]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64 
dtypes: int64(1), object(10)
memory usage: 918.2+ KB


In [9]:
train_data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [10]:
train_data.isnull().values.any()

True

## EDA on test_data

In [11]:
test_data.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info'],
      dtype='object')

In [12]:
test_data.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
dtype: object

In [13]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2671 entries, 0 to 2670
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          2671 non-null   object
 1   Date_of_Journey  2671 non-null   object
 2   Source           2671 non-null   object
 3   Destination      2671 non-null   object
 4   Route            2671 non-null   object
 5   Dep_Time         2671 non-null   object
 6   Arrival_Time     2671 non-null   object
 7   Duration         2671 non-null   object
 8   Total_Stops      2671 non-null   object
 9   Additional_Info  2671 non-null   object
dtypes: object(10)
memory usage: 208.8+ KB


In [14]:
test_data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
dtype: int64

In [15]:
test_data.isnull().values.any()

False

### Dropping the NaN value as there is only one NaN value

In [16]:
print('Original Length of Training dataset :', len(train_data))

train_data = train_data.dropna()

print('Length of Training dataset after dropping NaN :', len(train_data))

Original Length of Training dataset : 10683
Length of Training dataset after dropping NaN : 10682


### Converting the data type to date-time format and adding new columns

In [17]:
train_data['Date_of_Journey']

0        24/03/2019
1         1/05/2019
2         9/06/2019
3        12/05/2019
4        01/03/2019
            ...    
10678     9/04/2019
10679    27/04/2019
10680    27/04/2019
10681    01/03/2019
10682     9/05/2019
Name: Date_of_Journey, Length: 10682, dtype: object

In [18]:
train_data['Journey_Day'] = pd.to_datetime(train_data.Date_of_Journey, format='%d/%m/%Y').dt.day
train_data.head() # cheking the dataset after transformationtrain_data

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   
1    05:50         13:15   7h 25m     2 stops         No info   7662   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882   
3    18:05         23:30   5h 25m      1 stop         No info   6218   
4    16:50         21:35   4h 45m      1 stop         No info  13302   

   Journey_Day  
0           24  
1            1  
2            9  
3           12  
4            1

In [19]:
train_data['Journey_Month'] = pd.to_datetime(train_data.Date_of_Journey, format='%d/%m/%Y').dt.month
train_data.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   
1    05:50         13:15   7h 25m     2 stops         No info   7662   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882   
3    18:05         23:30   5h 25m      1 stop         No info   6218   
4    16:50         21:35   4h 45m      1 stop         No info  13302   

   Journey_Day  Journey_Month  
0           24              3  
1            1              5  
2            9              6  
3           12              5  
4            1              3

### date-time for test_data

In [20]:
test_data['Journey_Day'] = pd.to_datetime(test_data.Date_of_Journey, format='%d/%m/%Y').dt.day
test_data['Journey_Month'] = pd.to_datetime(test_data.Date_of_Journey, format='%d/%m/%Y').dt.month
test_data.head()

Airline Date_of_Journey    Source Destination            Route  \
0        Jet Airways       6/06/2019     Delhi      Cochin  DEL → BOM → COK   
1             IndiGo      12/05/2019   Kolkata    Banglore  CCU → MAA → BLR   
2        Jet Airways      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
3  Multiple carriers      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
4           Air Asia      24/06/2019  Banglore       Delhi        BLR → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops              Additional_Info  \
0    17:30  04:25 07 Jun  10h 55m      1 stop                      No info   
1    06:20         10:20       4h      1 stop                      No info   
2    19:15  19:00 22 May  23h 45m      1 stop  In-flight meal not included   
3    08:00         21:00      13h      1 stop                      No info   
4    23:55  02:45 25 Jun   2h 50m    non-stop                      No info   

   Journey_Day  Journey_Month  
0            6              6  
1           12              5  
2           21              5  
3           21              5  
4           24              6

### Compare the dates and delete the original date feature


In [21]:
train_data.drop(labels = 'Date_of_Journey', axis = 1, inplace = True)
train_data.head()

Airline    Source Destination                  Route Dep_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    22:20   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK    09:25   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR    18:05   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL    16:50   

   Arrival_Time Duration Total_Stops Additional_Info  Price  Journey_Day  \
0  01:10 22 Mar   2h 50m    non-stop         No info   3897           24   
1         13:15   7h 25m     2 stops         No info   7662            1   
2  04:25 10 Jun      19h     2 stops         No info  13882            9   
3         23:30   5h 25m      1 stop         No info   6218           12   
4         21:35   4h 45m      1 stop         No info  13302            1   

   Journey_Month  
0              3  
1              5  
2              6  
3              5  
4              3

In [22]:
test_data.drop(labels = 'Date_of_Journey', axis = 1, inplace = True)
test_data.head()

Airline    Source Destination            Route Dep_Time  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK    17:30   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR    06:20   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK    19:15   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK    08:00   
4           Air Asia  Banglore       Delhi        BLR → DEL    23:55   

   Arrival_Time Duration Total_Stops              Additional_Info  \
0  04:25 07 Jun  10h 55m      1 stop                      No info   
1         10:20       4h      1 stop                      No info   
2  19:00 22 May  23h 45m      1 stop  In-flight meal not included   
3         21:00      13h      1 stop                      No info   
4  02:45 25 Jun   2h 50m    non-stop                      No info   

   Journey_Day  Journey_Month  
0            6              6  
1           12              5  
2           21              5  
3           21              5  
4           24              6

In [23]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10682 entries, 0 to 10682
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Arrival_Time     10682 non-null  object
 6   Duration         10682 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  object
 9   Price            10682 non-null  int64 
 10  Journey_Day      10682 non-null  int64 
 11  Journey_Month    10682 non-null  int64 
dtypes: int64(3), object(9)
memory usage: 1.1+ MB


### Our duration column had time written in this format 2h 50m .To help machine learning algorithm derive useful insights, we will convert this text into numeric.


In [28]:
duration_train = list(train_data['Duration'])


for i in range(len(duration_train)) :
    if len(duration_train[i].split()) != 2: 
        if 'h' in duration_train[i] :
            duration_train[i] = duration_train[i].strip() + ' 0m'
        elif 'm' in duration_train[i] :
            duration_train[i] = '0h {}'.format(duration_train[i].strip())

dur_hours = []
dur_minutes = []  

for i in range(len(duration_train)) :
    dur_hours.append(int(duration_train[i].split()[0][:-1])) #for examole if duration is 49 mintutes 4 sec then it will reflect like 
    dur_minutes.append(int(duration_train[i].split()[1][:-1]))#0:49:4 and if 2 hours 10 seconds then it will reflect like 2:0:10
    
train_data['Duration_hours'] = dur_hours
train_data['Duration_minutes'] =dur_minutes

train_data.drop(labels = 'Duration', axis = 1, inplace = True) # dropping the original duration column from train_data


# Test Set(applyig same code to convert 'Duration' to 'Duration _Hours' and 'Duration_Minutes')
#2h 50m
duration_Test = list(test_data['Duration'])

for i in range(len(duration_Test)) :
    if len(duration_Test[i].split()[0]) != 2:       
        if 'h' in duration_Test[i] :
            duration_Test[i] = duration_Test[i].strip() + ' 0m'
        elif 'm' in duration_Test[i] :
            duration_Test[i] = '0h {}'.format(duration_Test[i].strip())
            
dur_hours = []
dur_minutes = []  

for i in range(len(duration_Test)) :
    #print(durationT[i].split())
    dur_hours.append(int(duration_Test[i].split()[0][:-1]))
    if(len(duration_Test[i].split())>1):
        dur_minutes.append(int(duration_Test[i].split()[1][:-1]))
    else:
        dur_minutes.append(int(0))
  
    
test_data['Duration_hours'] = dur_hours
test_data['Duration_minutes'] = dur_minutes
train_data
test_data.drop(labels = 'Duration', axis = 1, inplace = True) #  dropping the original duration column from test_data

KeyError: 'Duration'

In [27]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10682 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Airline           10682 non-null  object
 1   Source            10682 non-null  object
 2   Destination       10682 non-null  object
 3   Route             10682 non-null  object
 4   Dep_Time          10682 non-null  object
 5   Arrival_Time      10682 non-null  object
 6   Total_Stops       10682 non-null  object
 7   Additional_Info   10682 non-null  object
 8   Price             10682 non-null  int64 
 9   Journey_Day       10682 non-null  int64 
 10  Journey_Month     10682 non-null  int64 
 11  Duration_hours    10682 non-null  int64 
 12  Duration_minutes  10682 non-null  int64 
dtypes: int64(5), object(8)
memory usage: 1.1+ MB


### Converting Dep_Time to 'Depart_Time_hour' and 'Depart_time_Minutes'

In [29]:
train_data['Depart_Time_Hour'] = pd.to_datetime(train_data.Dep_Time).dt.hour
train_data['Depart_Time_Minutes'] = pd.to_datetime(train_data.Dep_Time).dt.minute

train_data.drop(labels = 'Dep_Time', axis = 1, inplace = True)

train_data.head()

Airline    Source Destination                  Route  Arrival_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL  01:10 22 Mar   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR         13:15   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK  04:25 10 Jun   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR         23:30   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL         21:35   

  Total_Stops Additional_Info  Price  Journey_Day  Journey_Month  \
0    non-stop         No info   3897           24              3   
1     2 stops         No info   7662            1              5   
2     2 stops         No info  13882            9              6   
3      1 stop         No info   6218           12              5   
4      1 stop         No info  13302            1              3   

   Duration_hours  Duration_minutes  Depart_Time_Hour  Depart_Time_Minutes  
0               2                50                22                   20  
1               7                25                 5                   50  
2              19                 0                 9                   25  
3               5                25                18                    5  
4               4                45                16                   50

In [33]:
test_data['Depart_Time_Hour'] = pd.to_datetime(test_data.Dep_Time).dt.hour
test_data['Depart_Time_Minutes'] = pd.to_datetime(test_data.Dep_Time).dt.minute

test_data.drop(labels = 'Dep_Time', axis = 1, inplace = True)

test_data.head()

Airline    Source Destination            Route Total_Stops  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK      1 stop   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR      1 stop   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK      1 stop   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK      1 stop   
4           Air Asia  Banglore       Delhi        BLR → DEL    non-stop   

               Additional_Info  Journey_Day  Journey_Month  Duration_hours  \
0                      No info            6              6              10   
1                      No info           12              5               4   
2  In-flight meal not included           21              5              23   
3                      No info           21              5              13   
4                      No info           24              6               2   

   Duration_minutes  Arr_Time_Hour  Arr_Time_Minute  Depart_Time_Hour  \
0                55              4               25                17   
1                 0             10               20                 6   
2                45             19                0                19   
3                 0             21                0                 8   
4                50              2               45                23   

   Depart_Time_Minutes  
0                   30  
1                   20  
2                   15  
3                    0  
4                   55

### Converting 'Arrival_Time' to 'Arr_Time_hour' and 'Arr_time_Minutes' and dropping the original column


In [31]:
train_data['Arr_Time_Hour'] = pd.to_datetime(train_data.Arrival_Time).dt.hour
train_data['Arr_Time_Minute'] = pd.to_datetime(train_data.Arrival_Time).dt.minute

train_data.drop(labels = 'Arrival_Time', axis = 1, inplace = True)
train_data.head()

Airline    Source Destination                  Route Total_Stops  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    non-stop   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR     2 stops   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK     2 stops   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR      1 stop   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL      1 stop   

  Additional_Info  Price  Journey_Day  Journey_Month  Duration_hours  \
0         No info   3897           24              3               2   
1         No info   7662            1              5               7   
2         No info  13882            9              6              19   
3         No info   6218           12              5               5   
4         No info  13302            1              3               4   

   Duration_minutes  Depart_Time_Hour  Depart_Time_Minutes  Arr_Time_Hour  \
0                50                22                   20              1   
1                25                 5                   50             13   
2                 0                 9                   25              4   
3                25                18                    5             23   
4                45                16                   50             21   

   Arr_Time_Minute  
0               10  
1               15  
2               25  
3               30  
4               35

In [32]:
test_data['Arr_Time_Hour'] = pd.to_datetime(test_data.Arrival_Time).dt.hour
test_data['Arr_Time_Minute'] = pd.to_datetime(test_data.Arrival_Time).dt.minute

test_data.drop(labels = 'Arrival_Time', axis = 1, inplace = True)
test_data.head()

Airline    Source Destination            Route Dep_Time  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK    17:30   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR    06:20   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK    19:15   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK    08:00   
4           Air Asia  Banglore       Delhi        BLR → DEL    23:55   

  Total_Stops              Additional_Info  Journey_Day  Journey_Month  \
0      1 stop                      No info            6              6   
1      1 stop                      No info           12              5   
2      1 stop  In-flight meal not included           21              5   
3      1 stop                      No info           21              5   
4    non-stop                      No info           24              6   

   Duration_hours  Duration_minutes  Arr_Time_Hour  Arr_Time_Minute  
0              10                55              4               25  
1               4                 0             10               20  
2              23                45             19                0  
3              13                 0             21                0  
4               2                50              2               45

## Analyzing the train_data and test_data

In [35]:
# 6 is the index of "Price" in the Training Set , setting it as the label column
Y_train = train_data.iloc[:,6].values

#Independent Variables for train_data
X_train = train_data.iloc[:, train_data.columns != 'Price'].values  # Select all columns except 'Price'

#Independent Variables for test_data
X_test = test_data.iloc[:,:].values

X_train

array([['IndiGo', 'Banglore', 'New Delhi', ..., 20, 1, 10],
       ['Air India', 'Kolkata', 'Banglore', ..., 50, 13, 15],
       ['Jet Airways', 'Delhi', 'Cochin', ..., 25, 4, 25],
       ...,
       ['Jet Airways', 'Banglore', 'Delhi', ..., 20, 11, 20],
       ['Vistara', 'Banglore', 'New Delhi', ..., 30, 14, 10],
       ['Air India', 'Delhi', 'Cochin', ..., 55, 19, 15]], dtype=object)

### From the info above it could be observed that many colmns are of object type. So, converting those categorical columns to numerical columns


In [36]:
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
le2 = LabelEncoder()

## For train_set

In [37]:
X_train[:,0] = le1.fit_transform(X_train[:,0])
X_train

array([[3, 'Banglore', 'New Delhi', ..., 20, 1, 10],
       [1, 'Kolkata', 'Banglore', ..., 50, 13, 15],
       [4, 'Delhi', 'Cochin', ..., 25, 4, 25],
       ...,
       [4, 'Banglore', 'Delhi', ..., 20, 11, 20],
       [10, 'Banglore', 'New Delhi', ..., 30, 14, 10],
       [1, 'Delhi', 'Cochin', ..., 55, 19, 15]], dtype=object)

In [38]:
X_train[:,1] = le1.fit_transform(X_train[:,1])
X_train

array([[3, 0, 'New Delhi', ..., 20, 1, 10],
       [1, 3, 'Banglore', ..., 50, 13, 15],
       [4, 2, 'Cochin', ..., 25, 4, 25],
       ...,
       [4, 0, 'Delhi', ..., 20, 11, 20],
       [10, 0, 'New Delhi', ..., 30, 14, 10],
       [1, 2, 'Cochin', ..., 55, 19, 15]], dtype=object)

In [39]:
X_train[:,2] = le1.fit_transform(X_train[:,2])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [40]:
X_train[:,3] = le1.fit_transform(X_train[:,3])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [41]:
X_train[:,4] = le1.fit_transform(X_train[:,4])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [42]:
X_train[:,5] = le1.fit_transform(X_train[:,5])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

### For test_data

In [43]:
X_test[:,0] = le1.fit_transform(X_test[:,0])
X_test[:,1] = le1.fit_transform(X_test[:,1])
X_test[:,2] = le1.fit_transform(X_test[:,2])
X_test[:,3] = le1.fit_transform(X_test[:,3])
X_test[:,4] = le1.fit_transform(X_test[:,4])
X_test[:,5] = le1.fit_transform(X_test[:,5])

X_test

array([[4, 2, 1, ..., 25, 17, 30],
       [3, 3, 0, ..., 20, 6, 20],
       [4, 2, 1, ..., 0, 19, 15],
       ...,
       [4, 2, 1, ..., 25, 21, 50],
       [1, 2, 1, ..., 15, 4, 0],
       [6, 2, 1, ..., 15, 4, 55]], dtype=object)

## Feature Scaling

In [44]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()

## Operations in X labels

In [45]:
X_train = sc_X.fit_transform(X_train)
X_train

array([[-0.41080484, -1.65835945,  2.41653414, ..., -0.2349499 ,
        -1.80043628, -0.8900139 ],
       [-1.26115217,  0.89001433, -0.97381203, ...,  1.36360731,
        -0.05090913, -0.5870944 ],
       [ 0.01436882,  0.04055641, -0.2957428 , ...,  0.0314763 ,
        -1.3630545 ,  0.0187446 ],
       ...,
       [ 0.01436882, -1.65835945,  0.38232644, ..., -0.2349499 ,
        -0.34249699, -0.2841749 ],
       [ 2.56541078, -1.65835945,  2.41653414, ...,  0.2979025 ,
         0.0948848 , -0.8900139 ],
       [-1.26115217,  0.04055641, -0.2957428 , ...,  1.63003351,
         0.82385444, -0.5870944 ]])

In [46]:
X_test = sc_X.fit_transform(X_test)
X_test

array([[ 0.01190758,  0.03256662, -0.29488167, ...,  0.02633999,
         0.77326478,  0.26770357],
       [-0.42377921,  0.87708559, -0.97622158, ..., -0.27177067,
        -1.16144462, -0.25632445],
       [ 0.01190758,  0.03256662, -0.29488167, ..., -1.46421332,
         1.12503013, -0.51833847],
       ...,
       [ 0.01190758,  0.03256662, -0.29488167, ...,  0.02633999,
         1.47679547,  1.31575963],
       [-1.29515278,  0.03256662, -0.29488167, ..., -0.56988133,
        -1.51320997, -1.30438051],
       [ 0.88328115,  0.03256662, -0.29488167, ..., -0.56988133,
        -1.51320997,  1.57777364]])

## Operations in Y labels

In [47]:
Y_train = Y_train.reshape((len(Y_train), 1))
Y_train = sc_X.fit_transform(Y_train)
Y_train = Y_train.ravel()
Y_train

array([-1.12553455, -0.30906781,  1.03978296, ..., -0.40296691,
        0.77218138,  0.57809433])

### Now the training and test datasets are seperated which can be used to build a machine learning model.